<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Page Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="http://brijesh.com/cupcake/public/css/bootstrap.css" rel="stylesheet">
        <link href="http://brijesh.com/cupcake/public/css/bootstrap-responsive.css" rel="stylesheet">
        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

        <?php
        //echo $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl() . '/js/example.js');
        // echo $this->headLink()->prependStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl() . '/css/add.css');
        ?>


        <style type="text/css" >
            .err{
                color:#FF0000;
            }
        </style>
        <!--[if IE ]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>
        <script type="text/javascript">

            $(document).ready(function() {
                $('#fname_err').text("");
                $('#lname_err').text("");
                $('#email_err').text("");
                $('#password_err').text("");
                $('#repassword_err').text("");
                               
               

                $('#registration').submit(function() {
                    var counter=false;
                    if($('#fname').val()=='0')
                        $('#fname_err').text("Please select section!");
                    else
                        $('#fname_err').text("");

                    if($('#lname').val()=='')
                        $('#lname_err').text("Please enter valid category!");
                    else
                        $('#lname_err').text("");
		    
                    if($('#email').val()=='')
                        $('#email_err').text("Please enter valid category!");
                    else
                        $('#email_err').text("");


                    if($('#password').val()=='')
                        $('#password_err').text("Please enter valid category!");
                    else
                        $('#password_err').text("");


                    if($('#repassword').val()!=$('#password').val())
                        $('#repassword_err').text("Please enter valid category!");
                    else
                        $('#repassword_err').text("");

                    if(($('#fname').val())&&($('#catrgory_name').val()!='')&&($('#catrgory_name_danish').val()!='')){
                        return true;
                    }
                    return false;

                });



                $('#back').click(function() {
                    window.location.href='<?php echo $this->url(array('controller' => 'article', 'action' => 'viewcategory'), null, true); ?>';
                });
                $('#category').click(function() {
                    var htamlString='';
                    if($('#section').val()!=''){
                        
                        $.ajax({
                            url: '<?php echo $this->url(array('controller' => 'article', 'action' => 'getcategory'), null, true); ?>?id='+$('#section').val(),
                            type: "GET",
                            dataType:"json",
                            success: function(data) {
                                //alert(data);
                                //$("#category").append("<option >select category</option>");
                                htamlString='';
                                for(var i=0;i<data.length;i++){
                                    htamlString+="<option value="+data[i].id+">"+data[i].name+"</option>";
                                }
                                $("#category").append(htamlString);
                            } 
                        });
                       
                    }    });
                $('#logout').click(function() {
                    window.location.href='<?php echo $this->url(array('controller' => 'index', 'action' => 'logout'), null, true); ?>';
                });
                $('#new').click(function() {
                    window.location.href='<?php echo $this->url(array('controller' => 'article', 'action' => 'add'), null, true); ?>';
                });
                $('#new_cat').click(function() {
                    window.location.href='<?php echo $this->url(array('controller' => 'article', 'action' => 'addcategory'), null, true); ?>';
                });
                $('#back').click(function() {
                    window.location.href='<?php echo $this->url(array('controller' => 'article', 'action' => 'viewcategory'), null, true); ?>';
                });
            });

        </script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="span8">
                    <form class="form-horizontal" id="registerHere" method='post' action=''>
                        <fieldset>

                            <legend>Registration</legend>
                            <div class="alert alert-success">

                            </div>           <div class="control-group">

                                <label class="control-label">Name</label>
                                <div class="controls">
                                    <input type="text" class="input-xlarge" id="user_name" name="user_name" rel="popover" data-content="Enter your first and last name." data-original-title="Full Name">
                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label">Email</label>
                                <div class="controls">
                                    <input type="text" class="input-xlarge" id="user_email" name="user_email" rel="popover" data-content="What’s your email address?" data-original-title="Email">
                                </div>
                            </div>


                            <div class="control-group">
                                <label class="control-label"></label>
                                <div class="controls">
                                    <button type="submit" class="btn btn-success" >Create My Account</button>
                                </div>
                            </div>

                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </body>
</html>